# Generated by Django 3.1.7 on 2021-04-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cateproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cateproduct',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='FormAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soa', models.CharField(max_length=255)),
                ('sob', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gia', models.FloatField()),
                ('image', models.CharField(max_length=50)),
                ('soluong', models.IntegerField()),
                ('mieuta', models.TextField()),
                ('giamgia', models.FloatField()),
                ('spmoi', models.IntegerField()),
                ('spdacbiet', models.IntegerField()),
                ('idcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cateproduct')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.customer')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.product')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('status', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giamgia', models.FloatField()),
                ('gia', models.FloatField()),
                ('slmua', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.customer')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.product')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.product')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
